### PR TITLE
empty directory remover(windows)

### PR DESCRIPTION
**Pull request by Krunal-Karena**
Please review my PR.

### CODE REVIEW

**Comment by Krunal-Karena** [comment]
Label it as Hacktoberfest accepted.

**Comment by ayaan-qadri** [comment]
Not working at all, It seem like you did copy paste

**Comment by Krunal-Karena** [comment]
Sorry i forgot to commit last changes but now it's working please reopen PR.

**Comment by Krunal-Karena** [comment]
if you open then i can commit new changes.

**Comment by ayaan-qadri** [comment]
@devshaki check EdRemver.py, What happens when user want to remove from everywhere and what happens when user want to remove from particular folder and implement it inside EdRemover.py rather than making other py file to repo, Py program that you made  that does not remove empty folder.

**Comment by Krunal-Karena** [comment]
after you reopen i commited some changes now check it.
Note : for particular folder you have to set "parent" because it delete only if it is in root directory.

**Comment by Krunal-Karena** [comment]
can you check it please ?

**Comment by Krunal-Karena** [comment]
hey @PentW0lf.

**Comment by ayaan-qadri** [comment]
Brother, You PR does not implemented well there is no loop to go through all folder, Can you pls learn how everything done in empty folder removing for Android.

**Comment by Krunal-Karena** [comment]
ok i will do it.

**Pull request closed without merging**
